### PR TITLE
Fix export related issues

### LINKED ISSUE #349: No 'export completed' message
When exporting as a MP4 has completed the progress bar goes away but there is nothing to indicate the export has been completed

### LINKED ISSUE #355: Keyboard shortcuts modal needs to be updated for export MP4
Currently the keyboard shortcuts menu, accessed via the 'Help' menu, is out of date. It only references export and does not specifically say export to EDL or MP4. Please add this.

### PR DESCRIPTION
**Pull request by zwan0202**
## Summary

- Updated export to EDL or MP4 keyboard shortcuts in keyboard shortcuts modal
- Added export complete message to indicate the export has been completed

<hr/>

### Why is this change needed?

To address issue [#349](https://github.com/MLVETDevelopers/mlvet/issues/349) and [#355 ](https://github.com/MLVETDevelopers/mlvet/issues/355)

<hr/>

### What did you change?

- Updated `KeyboardShortcutsDialog`
- Added an action and logic in reducer to `exportIo` to set `isExporting` to `false` for close export card
- Updated `ExportCard` to change text from `Exporting...` to `Export Complete` and added a close button when export progress reach 1. 
- Design to [Figma](https://www.figma.com/file/vPh49OC7hJpMD7cQMAnBUo/MLVET-UI-Design?node-id=2024%3A3531)

### Screenshots of UI changes, if any

Capture

<hr/>

### OS

- [ ] Linux
- [ ] MacOS
- [x] Windows

### CODE REVIEW

File: src/renderer/components/ExportCard.tsx [hunk 1]
```diff
@@ -9,18 +10,38 @@ const Card = styled(Stack)({
...
+  onClose: () => void;
   progress: number;
 }
 
-const ExportCard = ({ progress }: Props) => {
+const ExportCard = ({ onClose, progress }: Props) => {
+  const exportText = progress === 1 ? 'Export Complete' : 'Exporting...';
+  const closeButton =
+    progress === 1 ? (
+      <IconButton
```
Comment (Mhudlark) [inline src/renderer/components/ExportCard.tsx:25]: Mui has a component called IconButton which you can use. Sorry for not mentioning earlier 🤣 
https://mui.com/material-ui/react-button/
https://mui.com/material-ui/api/icon-button/

**Comment by Mhudlark** [comment]
Nice work! (This is first time mp4 export has properly worked for me and its f*cking great!) 
One little comment in code.
Couple of things when testing:
1. Noticed that export throws an error when project has not yet been saved. Could you please fix that (handle error or force save before export) in this PR?
image
2. `temp` folder from cuts is not deleted when individual cuts are deleted. Could you please fix that?

File: src/renderer/components/ExportCard.tsx (hunk 1 above)
Comment (zwan0202) [reply src/renderer/components/ExportCard.tsx:25]: It returns a `IconButton` when progress reaches 1, because we don't want it during the exporting

**Comment by zwan0202** [comment]
> Nice work! (This is first time mp4 export has properly worked for me and its f*** great!) One little comment in code. Couple of things when testing:
> 
> 1. Noticed that export throws an error when project has not yet been saved. Could you please fix that (handle error or force save before export) in this PR?
>    image
> 2. `temp` folder from cuts is not deleted when individual cuts are deleted. Could you please fix that?

1. So we are not allowing users to export when the project is not saved? (sorry i'm not sure how other app handle this)
2. I thought we decided just keep `temp` folder after export

File: src/renderer/components/ExportCard.tsx (hunk 1 above)
Comment (Mhudlark) [reply src/renderer/components/ExportCard.tsx:25]: Yeah I just meant use the MUI IconButton component rather than defining your own. Just more concise that way and its not an extra package.

**Review by Mhudlark — APPROVED** [review]
Great work!

**Comment by chloebrett** [comment]
I feel like it should be fine to allow export even if the project isn't saved - other software does this. Just use the media path as the default save location instead of the project file path in that case

**Review by emmapainter — APPROVED** [review]
Agreed that being able to export without saving would be ideal. Given we are two days out from the deadline feel free to merge this as is @zwan0202 since I think the current state is fine, but if you have time you can change it to align with Chloe's suggestion.
